### ISSUE TITLE
Works except it won't allow me to add the card in Authenticator

### ISSUE THREAD

**Issue by kocho-tomu** [Azure-Samples/active-directory-verifiable-credentials-dotnet#31] opened 2022-08-11 16:15 UTC
### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Setup as per documentation
Run the sample app, launch the page via ngrok, try to GET CREDENTIAL
QR code appears and can be scanned. The code is accepted but the 'Add' button in Authenticator is greyed out

### Any log messages given by the failure
> Nope, stuck on "QR Code is scanned. Waiting for issuance..."

### Expected/desired behavior
> Add button is not greyed out > credential can be added to app

### OS and Version?
> Android 12

### Versions
> Authenticator v6.2207.4624

### Mention any other details that might be useful
I have setup 1-asp-net-core-api-idtokenhint without issue and can Add credentials there just fine

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by kocho-tomu** [comment] 2022-08-12 08:02
Actually this is similar to the other open bug

**Comment by kocho-tomu** [comment] 2022-08-15 13:13
Now I can't even authenticate into AAD as it is trying to redirect to a HTTP address and AAD doesn't let me add a non-HTTPS URL to an app:

AADSTS50011: The redirect URI 'http://3aa2-193-117-237-244.eu.ngrok.io/signin-oidc' specified in the request does not match the redirect URIs configured for the application '8999e576-b238-4ffc-90b9-7ccd8cc6aac6'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

My published page in ngrok is HTTPS, so why is it going to a HTTP redirect? Thanks

**Comment by cljung** [comment] 2022-08-17 16:12
The sample works and the problems you are facing are most probably due to your configuration. 
Please ask developer related questions on https://stackoverflow.com and tag them with _azure-ad-verifiable-credentials_.
Closing this issue

**Closed by cljung** 2022-08-17 16:12 UTC

**Comment by kocho-tomu** [comment] 2022-08-18 07:32
Hmm but I haven't changed it much and followed the instructions (no issues with the other sample) but can try again...

**Comment by kocho-tomu** [comment] 2022-08-18 10:56
Hi @cljung 

OK so I've set it all up from scratch and have followed the instructions without developmental changes. I can sign in and generate a QR code fine again, but still I cannot add it to the app. It scans and shows the card, I can enter the PIN but then the Add button is greyed out.

The VSCode Debug Console just shows "QR Code is scanned. Waiting for issuance...".

What else could be wrong here please? Can you please confirm the current sample is working in this regard for you?

Thanks

**Comment by cljung** [comment] 2022-08-30 12:33
@kocho-tomu - yes, I can confirm that both issuance and presentation works. As you do not get further with issuing your VC, there is something incorrect in your credential contract (display & rules) or in combination with the settings you have in appsettings.json. Please ask these types of questions at https://stackoverflow.com/ and tag them with tag #azure-ad-verifiable-credentials.

**Comment by kocho-tomu** [comment] 2022-08-30 12:35
Thanks all good now, Matthijs saved me in the end (was a combination of changes my side and to the sample!)
